services:
#    pbxg33k_vocadb.example:
#        class: Pbxg33k\VocadbBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    pbxg33k_vocadb.admin.artist:
        class: Pbxg33k\VocadbBundle\Admin\ArtistAdmin
        arguments: [~, Pbxg33k\VocadbBundle\Entity\Artist, Pbxg33kVocadbBundle:Admin/ArtistAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: VocaDB, label: Artist}

    pbxg33k_vocadb.admin.song:
        class: Pbxg33k\VocadbBundle\Admin\SongAdmin
        arguments: [~, Pbxg33k\VocadbBundle\Entity\Song, Pbxg33kVocadbBundle:Admin/SongAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: VocaDB, label: Song}

    pbxg33k_vocadb.admin.album:
        class: Pbxg33k\VocadbBundle\Admin\AlbumAdmin
        arguments: [~, Pbxg33k\VocadbBundle\Entity\Album, Pbxg33kVocadbBundle:Admin/AlbumAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: VocaDB, label: Album}

    pbxg33k_vocadb.admin.artist.type:
        class: Pbxg33k\VocadbBundle\Admin\Artist\TypeAdmin
        arguments: [~, Pbxg33k\VocadbBundle\Entity\Artist\Type, Pbxg33kVocadbBundle:Admin/Artist/TypeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: VocaDB - Artist, label: Type}

    pbxg33k_vocadb.admin.album.artist:
        class: Pbxg33k\VocadbBundle\Admin\Album\ArtistAdmin
        arguments: [~, Pbxg33k\VocadbBundle\Entity\Album\Artist, Pbxg33kVocadbBundle:Admin/Album/ArtistAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: VocaDB - Album, label: Artist}

    pbxg33k_vocadb.admin.album.track:
        class: Pbxg33k\VocadbBundle\Admin\Album\TrackAdmin
        arguments: [~, Pbxg33k\VocadbBundle\Entity\Album\Track, Pbxg33kVocadbBundle:Admin/Album/TrackAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: VocaDB - Album, label: Track}

